# Generated by Django 5.2 on 2025-04-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_drive_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_drive_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
