# Generated by Django 5.2 on 2025-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_diagram_google_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='name',
            field=models.CharField(default='New Flowchart Diagram', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='diagram',
            unique_together={('user', 'name')},
        ),
    ]
